id: AssetManager
name: AssetManager
version: 0.1
description: Asset manager
author_name: 'Kenichi Naito'

applications:
    cms:
        methods:
            asset_manager: $AssetManager::AssetManager::Plugin::hndl_method
#            asset_manager: $AssetManager::AssetManager::Plugin::hndl_form

list_properties:
	asset:
		file_path:
			label: パス
			auto: 1
			display: default
			bulk_html: $AssetManager::AssetManager::Plugin::file_path_bulk_html
		url:
			label: URL
			auto: 1

list_actions:
	asset:
		change_path:
			label: パスの変更
			js_message: change path
#			code: $AssetManager::AssetManager::Plugin::action_code
			no_prompt: 1
			condition: $AssetManager::AssetManager::Plugin::action_condition
			mode: asset_manager
            
